### ISSUE TITLE
Read my browsing history

### ISSUE THREAD

**Issue by lcutler** [sudonatalie/layout-trello#33] opened 2017-07-15 16:43 UTC
Permissions say "Read my browsing history" 

Can you please explain what this is? Is it every time I browse anything on my Google Chrome account, it gets sent to List Layout?

Thanks

**Comment by natchou** [comment] 2017-08-27 17:33
This must be an effect of using the "tabs" API, which allows the extension to check the URL of the page you're currently visiting. This extension only uses that API to check whether you're on a Trello board page (https://github.com/natchou/layout-trello/blob/master/background.js). If I remember correctly, I had to add the usage of this API because the "\*://trello.com/b/\*" permission alone wasn't catching navigation within the Trello site as a URL change, so the extension would sometimes be disabled until you refreshed the page.

I'm leaving this issue open as a reminder to look into alternative solutions to this problem that won't require such overarching permissions.

**Comment by andrewbrey** [comment] 2018-07-08 04:14
I would recommend you take a look at the "declarativeContent" permission. I've used it in an extension I've built for YouTube, but the concept is similar. See https://github.com/andrewbrey/youtube-speed-memory/blob/master/app/scripts.babel/background.js for an example of how I've used it. For reference, you are correct that the "tabs" permission is what is making the browser report that the extension needs to see your browsing history, and by using the declarativeContent permission, you can get much the same benefits as using tabs, but without this warning.

**Comment by sudonatalie** [comment] 2019-07-27 22:24
Current permissions state summarized in #51.

**Comment by sudonatalie** [comment] 2019-07-27 22:24
Duplicate of #51

**Closed by sudonatalie** 2019-07-27 22:24 UTC
Labels: feature
