### ISSUE TITLE
trello list organizer

### ISSUE THREAD

**Issue by lerouxcreek** [sudonatalie/layout-trello#40] opened 2018-02-09 12:11 UTC
I have downloaded the chrome extension but every time I click on the icon, it takes me back to your page!  I really want to use this trello list organizer.  please help

**Comment by sudonatalie** [comment] 2018-03-29 06:41
I expect this is a duplicate of #36. Resolving in favour of a single tracking issue.

**Closed by sudonatalie** 2018-03-29 06:41 UTC

**Comment by sudonatalie** [comment] 2018-03-29 06:42
Duplicate of #36
