### ISSUE TITLE
Macs

### ISSUE THREAD

**Issue by timviles** [sudonatalie/layout-trello#39] opened 2018-02-04 08:48 UTC
I love Trello Lists on a PC and set it up with my wife and mother in law on their macs.  For some reason despite apple-shift-R, checking it is enabled in Chrome extensions and rebooting I embarrassingly cannot it to work.  Surely a user error but how?

**Comment by sudonatalie** [comment] 2018-03-29 06:43
Duplicate of #36. Resolving in favour of a single tracking issue.

**Closed by sudonatalie** 2018-03-29 06:43 UTC
