### ISSUE TITLE
List Layouts for Trello won't stay stacked

### ISSUE THREAD

**Issue by jeannierivers** [sudonatalie/layout-trello#57] opened 2020-05-25 16:38 UTC
I've been using List Layouts for Trello for years.  Suddenly it stopped stacking my lists in rows.  

I uninstalled and reinstalled and now it will stack.

However, if I close Trello and re-open, I have to hit the icon to stack the lists again in each board.

In the past, they stayed stacked in rows.  

Are there plans to fix this glitch?  Or is there something I am not doing on my end so that the lists stay permanently in rows?

Thank you for your help!

**Comment by sudonatalie** [comment] 2020-05-25 19:33
Can you go provide error logs by following these steps?

1. Open `chrome://extensions`.
2. Click "Details" under "List Layouts for Trello".
3. Turn on "Collect errors".
4. Close and reopen Chrome.
5. Open Trello, toggle the list layout, close Trello. Repeat.
6. Open `chrome://extensions`.
7. Click "Errors" under "List Layouts for Trello".
8. Copy and paste the results here.

**Comment by jeannierivers** [comment] 2020-05-26 16:09
Hi.  thank you for your quick response.

I followed your directions exactly, but there is nothing that says "Errors" when I go back into the extension.  I've attached a screen shot. 

What am I missing?
![List Layouts for Trello screenshot 1](https://user-images.githubusercontent.com/65914339/82923963-aa7d7880-9f49-11ea-8fe4-223425aedf1a.png)
![List Layouts for Trello screenshot 2](https://user-images.githubusercontent.com/65914339/82923960-aa7d7880-9f49-11ea-8ca1-3ca7b1d601f1.png)

**Comment by shegs** [comment] 2020-06-09 14:09
multiple people (if not all) in our company also have this same issue.

**Comment by sudonatalie** [comment] 2020-06-14 20:57
@TSI-Publisher Interesting that refreshing the page fixes the issue. There haven't been any recent updates to this extension, so it sounds like there's been a change to Trello or a Chrome API that means the initialization script is no longer being triggered on first page load. 

1. When you close and re-open Chrome, how do you re-open Trello? (i.e. typing the URL, restoring closed tabs, etc.)
2. Can you paste here the first 3 lines from `chrome://version` (Google Chrome, Revision and OS)?

**Comment by TSI-Publisher** [comment] 2020-06-15 16:49
Hi, Natalie.
Thank you for your quick response.
I will try to answer your questions:

  1.  I have a few pages that I have Chrome set up to load whenever I open it. Trello is one of those pages.
  2.  Google Chrome 83.0.4103.97 (Official Build) (64-bit) (cohort: Stable)
  3.  Revision 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
  4.  Windows 10 OS Version 1909 (Build 18363.476)

**Comment by jeannierivers** [comment] 2020-06-15 17:22
Hi, Natalie.

1.  For me, I have a desktop shortcut to open Trello in Chrome.

2. First 3 lines:
Google Chrome | 83.0.4103.97 (Official Build) (64-bit) (cohort: Stable) 
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS | Windows 10 OS Version 1909 (Build 18363.900)

Thank you,
Jeannie

> @TSI-Publisher Interesting that refreshing the page fixes the issue. There haven't been any recent updates to this extension, so it sounds like there's been a change to Trello or a Chrome API that means the initialization script is no longer being triggered on first page load.
> 
> 1. When you close and re-open Chrome, how do you re-open Trello? (i.e. typing the URL, restoring closed tabs, etc.)
> 2. Can you paste here the first 3 lines from `chrome://version` (Google Chrome, Revision and OS)?

**Comment by jeannierivers** [comment] 2020-06-23 15:39
Hi!  Any update on resolving this issue?

**Comment by TSI-Publisher** [comment] 2020-06-23 19:57
Thank you so much for checking in.
Another, much-larger issue has come up in our cloud-based back-up which has demanded all of our attention lately.
The issue of Trello cards not staying “stacked” has become much less of an aggravation.
It is easily worked around by clicking on the Lists icon, or refreshing the page.
Again, thanks for your time and concern,
Bill

_________________________________

Bill Newman
Publisher

TEACH Services, Inc.
11 Quartermaster Circle
Fort Oglethorpe, GA 30742-3886

**Comment by jeannierivers** [comment] 2020-06-24 17:33
Yikes, Bill! I feel like I've been smacked and sent to bed without supper!  LOL!  

Of course we're all using the workaround of clicking on the Lists icon.  

I wish you success on working out the "much-larger issue."

But I can't help but hope that you won't forget about us and that you'll eventually get around to this smaller issue too.  

Jeannie

**Comment by sudonatalie** [comment] 2020-06-25 01:14
There seems to be some confusion here, so just to clarify, @jeannierivers  and @TSI-Publisher, I think you are both users of the extension, not contributors that have worked on the development of it as far as I know.

I'm the owner of the extension, but it's a low-priority maintenance project for me, so no guarantees about when/if this issue will be fixed. If anyone who's able to reproduce the issue has the ability to contribute a fix sooner, I'd be happy to review and accept pull requests.

**Comment by jeannierivers** [comment] 2020-06-25 13:49
@sudonatalie Thank you, Natalie, for clarifying.  

Yes, I'm just a user.  

I love your extension; it's been of immense help to myself and my business.  I understand that issues are of higher priority than others.  Thank you for keeping this issue on your list of maintenance projects.

Take care and stay safe,
Jeannie

**Comment by BMannell** [comment] 2020-12-02 19:09
I'm having this issue as well. It seems to be stemming from reading chrome.storage in the syncState function.
![image](https://user-images.githubusercontent.com/5941447/100919351-b1141c00-34a7-11eb-8b7f-3605e720a93b.png)
My Chrome is at version 87.0.4280.66

**Comment by sudonatalie** [comment] 2021-03-09 00:41
I haven't heard any reports of this for a while, so I suspect it was caused by a bug in Chrome or a change in Trello that was fixed/reverted. If anyone here is still experiencing this issue, please comment or re-open.

**Closed by sudonatalie** 2021-03-09 00:41 UTC
