### ISSUE TITLE
Grid Layout Not Working Properly

### ISSUE THREAD

**Issue by danielusher1** [sudonatalie/layout-trello#70] opened 2023-10-16 16:17 UTC
The grid view used to display the second row of boards so it was visible above the fold.  Now, the second row is below the fold.  I've uninstalled and re-installed List Layout for Trello and even tried using other extensions and deleted List Layout for Trello and the second row is still below the fold and I have to scroll down to see it.  I created another Trello account on a different Chromebook with a different login and the same thing is happening.  I removed List layout for Trello and added Trello Grids extension and still the same thing is happening, so it is not the applications or my computer or account, but something with Trello or maybe Chromebook.  Any help would be appreciated.  Thanks, Dan

**Comment by sudonatalie** [comment] 2023-10-24 00:16
Thanks for reporting. Closing as a duplicate of #69.

As I mentioned there, I don't have a lot of time to dedicate to maintaining this extension and am personally no longer actively using it so I can't make any promises about when or if it will be fixed. I've unpublished it from the Chrome Web Store for the time being. I'm open to Pull Requests if any devs out there want to dig into the CSS changes.

**Closed by sudonatalie** 2023-10-24 00:16 UTC

**Comment by jfauswisc** [comment] 2023-10-24 12:25
Hi Natalie! Thanks for the reply. Do you have another similar feature you use to get similar results? I find this one so helpful with how many cards I have and will hate to go back to a strictly horizontal layout, but have no CSS skills to speak of. Thanks much!

**Comment by sudonatalie** [comment] 2023-10-31 00:35
To update folks here too, I'm no longer going to maintain this Chrome extension, but I fixed the CSS and uploaded it as [Stylish](https://chrome.google.com/webstore/detail/stylish-custom-themes-for/fjnbnpbmkenffdnngjfgmeleoegfcffe) themes that you can install here (pick one):

* [Grid Layout for Trello](https://userstyles.org/styles/271254/grid-layout-for-trello)
* [Vertical Layout for Trello](https://userstyles.org/styles/271256/vertical-layout-for-trello)

Hope that helps!

**Comment by danielusher1** [comment] 2023-11-02 14:05
Thanks Natalie!  The new version you uploaded to Stylish works great.  Thanks again, Dan
