### ISSUE TITLE
Number of cards shown in each list in Grid View

### ISSUE THREAD

**Issue by JamieJ1** [sudonatalie/layout-trello#45] opened 2018-06-06 04:13 UTC
Would it be possible to edit the max number of cards that show within each "cell" of the grid view. 
ie, would it be possible to show only 2 cards per List rather than the current 5?

**Comment by sudonatalie** [comment] 2018-06-11 03:52
Closing as duplicate of Issue #13. Unlikely to be addressed anytime soon, but I'll leave it open as a feature request.

**Closed by sudonatalie** 2018-06-11 03:52 UTC
